### ISSUE TITLE
Custom DataLoader

### ISSUE THREAD

**Issue by dfayzur** [narumiruna/efficientnet-pytorch#15]
Hi,

Thank you very much for the repo. Do you have an script for custom dataloader?

Thanks

**Comment by narumiruna** [comment]
Hi,

Here is the example to create custom dataloader: https://github.com/narumiruna/efficientnet-pytorch/commit/72d7232ef85d9a7214b838d13be389a640e8f749

**Comment by dfayzur** [comment]
Thank you very much for such a quick example.
